{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e0f9bdc5-8ae4-4385-8104-a22b89806122",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "\n",
    "# =========================================================\n",
    "# PAGE CONFIG\n",
    "# =========================================================\n",
    "st.set_page_config(\n",
    "    page_title=\"AI Diabetes Intelligence Dashboard\",\n",
    "    page_icon=\"🩺\",\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"expanded\"\n",
    ")\n",
    "\n",
    "# =========================================================\n",
    "# CUSTOM CSS\n",
    "# =========================================================\n",
    "st.markdown(\"\"\"\n",
    "<style>\n",
    ".main {\n",
    "    background: linear-gradient(135deg,#07121F,#0B1F3A);\n",
    "}\n",
    "\n",
    "[data-testid=\"stSidebar\"] {\n",
    "    background: linear-gradient(180deg,#081229,#102B50);\n",
    "}\n",
    "\n",
    "h1,h2,h3 {\n",
    "    color: white;\n",
    "}\n",
    "</style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# =========================================================\n",
    "# LOAD DATA\n",
    "# =========================================================\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "\n",
    "    # CSV file\n",
    "    demo_df = pd.read_csv(\"cleaned_demographics.csv\")\n",
    "\n",
    "    # Excel XLSB file\n",
    "    diabetes_df = pd.read_excel(\n",
    "        \"cleaned_hupa_diabetes_recent.xlsb\",\n",
    "        engine=\"pyxlsb\"\n",
    "    )\n",
    "\n",
    "    # OPTIONAL: merge (if common key exists like patient_id)\n",
    "    if \"patient_id\" in demo_df.columns and \"patient_id\" in diabetes_df.columns:\n",
    "        df = diabetes_df.merge(demo_df, on=\"patient_id\", how=\"left\")\n",
    "    else:\n",
    "        df = diabetes_df.copy()\n",
    "\n",
    "    # Ensure datetime column exists\n",
    "    if \"time\" in df.columns:\n",
    "        df[\"time\"] = pd.to_datetime(df[\"time\"])\n",
    "        df[\"hour\"] = df[\"time\"].dt.hour\n",
    "\n",
    "    # Feature engineering (safe checks)\n",
    "    if \"glucose\" in df.columns:\n",
    "        df[\"glucose_roc\"] = df[\"glucose\"].diff()\n",
    "\n",
    "        df[\"glucose_rolling_std\"] = (\n",
    "            df[\"glucose\"].rolling(12).std().fillna(0)\n",
    "        )\n",
    "\n",
    "    return df\n",
    "\n",
    "df = load_data()\n",
    "\n",
    "# =========================================================\n",
    "# SIDEBAR\n",
    "# =========================================================\n",
    "st.sidebar.title(\"🧠 AI Dashboard\")\n",
    "\n",
    "menu = st.sidebar.radio(\n",
    "    \"Navigation\",\n",
    "    [\"Overview\", \"Analytics\", \"Insights\"]\n",
    ")\n",
    "\n",
    "if \"patient_id\" in df.columns:\n",
    "    patient = st.sidebar.selectbox(\n",
    "        \"Select Patient\",\n",
    "        [\"All\"] + list(df[\"patient_id\"].unique())\n",
    "    )\n",
    "\n",
    "    if patient != \"All\":\n",
    "        df = df[df[\"patient_id\"] == patient]\n",
    "\n",
    "# =========================================================\n",
    "# HEADER\n",
    "# =========================================================\n",
    "st.title(\"🩺 AI Diabetes Intelligence Dashboard\")\n",
    "\n",
    "st.markdown(\"Real dataset-based clinical analytics system\")\n",
    "\n",
    "# =========================================================\n",
    "# KPI METRICS\n",
    "# =========================================================\n",
    "col1, col2, col3 = st.columns(3)\n",
    "\n",
    "if \"glucose\" in df.columns:\n",
    "    col1.metric(\"Avg Glucose\", round(df[\"glucose\"].mean(), 2))\n",
    "\n",
    "if \"heart_rate\" in df.columns:\n",
    "    col2.metric(\"Avg Heart Rate\", round(df[\"heart_rate\"].mean(), 2))\n",
    "\n",
    "if \"steps\" in df.columns:\n",
    "    col3.metric(\"Avg Steps\", int(df[\"steps\"].mean()))\n",
    "\n",
    "# =========================================================\n",
    "# OVERVIEW\n",
    "# =========================================================\n",
    "if menu == \"Overview\":\n",
    "\n",
    "    st.subheader(\"📊 Dataset Overview\")\n",
    "\n",
    "    if \"glucose\" in df.columns and \"time\" in df.columns:\n",
    "\n",
    "        fig = px.line(\n",
    "            df,\n",
    "            x=\"time\",\n",
    "            y=\"glucose\",\n",
    "            title=\"Glucose Trend\"\n",
    "        )\n",
    "\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "    if \"glucose\" in df.columns:\n",
    "\n",
    "        fig2 = px.histogram(\n",
    "            df,\n",
    "            x=\"glucose\",\n",
    "            title=\"Glucose Distribution\"\n",
    "        )\n",
    "\n",
    "        st.plotly_chart(fig2, use_container_width=True)\n",
    "\n",
    "# =========================================================\n",
    "# ANALYTICS\n",
    "# =========================================================\n",
    "elif menu == \"Analytics\":\n",
    "\n",
    "    st.subheader(\"📈 Analytics View\")\n",
    "\n",
    "    if all(col in df.columns for col in [\"glucose\", \"heart_rate\"]):\n",
    "\n",
    "        fig = px.scatter(\n",
    "            df,\n",
    "            x=\"heart_rate\",\n",
    "            y=\"glucose\",\n",
    "            title=\"Heart Rate vs Glucose\"\n",
    "        )\n",
    "\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "    if \"glucose_rolling_std\" in df.columns:\n",
    "\n",
    "        fig2 = px.line(\n",
    "            df,\n",
    "            y=\"glucose_rolling_std\",\n",
    "            title=\"Glucose Variability\"\n",
    "        )\n",
    "\n",
    "        st.plotly_chart(fig2, use_container_width=True)\n",
    "\n",
    "# =========================================================\n",
    "# INSIGHTS\n",
    "# =========================================================\n",
    "elif menu == \"Insights\":\n",
    "\n",
    "    st.subheader(\"🧠 AI Insights\")\n",
    "\n",
    "    if \"glucose\" in df.columns:\n",
    "\n",
    "        risk = df[\"glucose\"].mean()\n",
    "\n",
    "        if risk > 180:\n",
    "            st.error(\"High average glucose detected → risk of hyperglycemia\")\n",
    "        elif risk < 70:\n",
    "            st.warning(\"Low glucose detected → hypoglycemia risk\")\n",
    "        else:\n",
    "            st.success(\"Glucose levels are stable\")\n",
    "\n",
    "    st.markdown(\"\"\"\n",
    "    ### Clinical Insights:\n",
    "    - Glucose variability indicates instability\n",
    "    - Activity improves insulin sensitivity\n",
    "    - Continuous monitoring improves outcomes\n",
    "    \"\"\")\n",
    "\n",
    "# =========================================================\n",
    "# FOOTER\n",
    "# =========================================================\n",
    "st.markdown(\"---\")\n",
    "st.caption(\"AI Diabetes Dashboard | Streamlit + Plotly\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
