{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e0f9bdc5-8ae4-4385-8104-a22b89806122",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "from plotly.subplots import make_subplots\n",
    "\n",
    "# =========================================================\n",
    "# PAGE CONFIG\n",
    "# =========================================================\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"AI Diabetes Intelligence Dashboard\",\n",
    "    page_icon=\"🩺\",\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"expanded\"\n",
    ")\n",
    "\n",
    "# =========================================================\n",
    "# CUSTOM CSS\n",
    "# =========================================================\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "<style>\n",
    "\n",
    ".main {\n",
    "    background: linear-gradient(135deg,#07121F,#0B1F3A);\n",
    "}\n",
    "\n",
    "[data-testid=\"stSidebar\"] {\n",
    "    background: linear-gradient(180deg,#081229,#102B50);\n",
    "    border-right: 1px solid #1E3A5F;\n",
    "}\n",
    "\n",
    "h1,h2,h3,h4 {\n",
    "    color: white;\n",
    "    font-family: 'Segoe UI';\n",
    "}\n",
    "\n",
    ".metric-card {\n",
    "    background: rgba(17,45,78,0.85);\n",
    "    backdrop-filter: blur(8px);\n",
    "    padding: 20px;\n",
    "    border-radius: 18px;\n",
    "    border: 1px solid rgba(255,255,255,0.1);\n",
    "    box-shadow: 0 8px 24px rgba(0,0,0,0.3);\n",
    "}\n",
    "\n",
    ".insight-box {\n",
    "    background: rgba(17,45,78,0.85);\n",
    "    padding: 20px;\n",
    "    border-radius: 18px;\n",
    "    border-left: 5px solid #4FC3F7;\n",
    "    color: white;\n",
    "}\n",
    "\n",
    "div.stButton > button {\n",
    "    width: 100%;\n",
    "    border-radius: 12px;\n",
    "    background: linear-gradient(90deg,#00B4DB,#0083B0);\n",
    "    color: white;\n",
    "    border: none;\n",
    "    font-weight: bold;\n",
    "    padding: 10px;\n",
    "}\n",
    "\n",
    "div.stButton > button:hover {\n",
    "    background: linear-gradient(90deg,#0083B0,#00B4DB);\n",
    "    color: white;\n",
    "}\n",
    "\n",
    "[data-testid=\"metric-container\"] {\n",
    "    background: rgba(17,45,78,0.85);\n",
    "    border-radius: 18px;\n",
    "    padding: 15px;\n",
    "    border: 1px solid rgba(255,255,255,0.08);\n",
    "    box-shadow: 0 4px 16px rgba(0,0,0,0.25);\n",
    "}\n",
    "\n",
    "</style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# =========================================================\n",
    "# LOAD DATA\n",
    "# =========================================================\n",
    "\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "\n",
    "    np.random.seed(42)\n",
    "\n",
    "    time = pd.date_range(\n",
    "        start='2026-01-01',\n",
    "        periods=500,\n",
    "        freq='H'\n",
    "    )\n",
    "\n",
    "    df = pd.DataFrame({\n",
    "        'time': time,\n",
    "        'glucose': np.random.normal(140, 35, 500),\n",
    "        'heart_rate': np.random.normal(75, 10, 500),\n",
    "        'steps': np.random.randint(0, 12000, 500),\n",
    "        'calories': np.random.randint(1500, 3500, 500),\n",
    "        'sleep_hours': np.random.normal(7, 1, 500),\n",
    "        'carb_input': np.random.randint(0, 100, 500),\n",
    "        'insulin': np.random.randint(5, 30, 500),\n",
    "        'patient_id': np.random.choice(\n",
    "            ['P101','P102','P103','P104'],\n",
    "            500\n",
    "        )\n",
    "    })\n",
    "\n",
    "    df['glucose_roc'] = df['glucose'].diff()\n",
    "\n",
    "    df['glucose_rolling_std'] = (\n",
    "        df['glucose']\n",
    "        .rolling(12)\n",
    "        .std()\n",
    "        .fillna(0)\n",
    "    )\n",
    "\n",
    "    df['hour'] = df['time'].dt.hour\n",
    "\n",
    "    return df\n",
    "\n",
    "df = load_data()\n",
    "\n",
    "# =========================================================\n",
    "# SIDEBAR\n",
    "# =========================================================\n",
    "\n",
    "st.sidebar.title(\"🧠 AI Analytics\")\n",
    "\n",
    "menu = st.sidebar.radio(\n",
    "    \"Navigation\",\n",
    "    [\n",
    "        \"Overview\",\n",
    "        \"Descriptive Analytics\",\n",
    "        \"Predictive Analytics\",\n",
    "        \"Prescriptive Analytics\"\n",
    "    ]\n",
    ")\n",
    "\n",
    "patient = st.sidebar.selectbox(\n",
    "    \"Select Patient\",\n",
    "    ['All'] + list(df['patient_id'].unique())\n",
    ")\n",
    "\n",
    "if patient != 'All':\n",
    "    df = df[df['patient_id'] == patient]\n",
    "\n",
    "# =========================================================\n",
    "# HEADER\n",
    "# =========================================================\n",
    "\n",
    "st.title(\"🩺 AI-Powered Diabetes Intelligence Dashboard\")\n",
    "st.markdown(\"### Real-Time CGM Monitoring & Predictive Analytics\")\n",
    "\n",
    "# =========================================================\n",
    "# KPI SECTION\n",
    "# =========================================================\n",
    "\n",
    "col1, col2, col3, col4 = st.columns(4)\n",
    "\n",
    "tir = ((df['glucose'].between(70,180)).mean()) * 100\n",
    "\n",
    "with col1:\n",
    "    st.metric(\n",
    "        \"Average Glucose\",\n",
    "        f\"{round(df['glucose'].mean(),1)} mg/dL\"\n",
    "    )\n",
    "\n",
    "with col2:\n",
    "    st.metric(\n",
    "        \"Time In Range\",\n",
    "        f\"{round(tir,1)}%\"\n",
    "    )\n",
    "\n",
    "with col3:\n",
    "    st.metric(\n",
    "        \"Average Heart Rate\",\n",
    "        f\"{round(df['heart_rate'].mean(),1)} bpm\"\n",
    "    )\n",
    "\n",
    "with col4:\n",
    "    st.metric(\n",
    "        \"Average Steps\",\n",
    "        f\"{int(df['steps'].mean())}\"\n",
    "    )\n",
    "\n",
    "# =========================================================\n",
    "# OVERVIEW\n",
    "# =========================================================\n",
    "\n",
    "if menu == \"Overview\":\n",
    "\n",
    "    st.subheader(\"📘 Dataset Overview\")\n",
    "\n",
    "    col1, col2 = st.columns(2)\n",
    "\n",
    "    with col1:\n",
    "\n",
    "        fig_glucose = px.line(\n",
    "            df,\n",
    "            x='time',\n",
    "            y='glucose',\n",
    "            color='patient_id',\n",
    "            template='plotly_dark',\n",
    "            title='Glucose Trends'\n",
    "        )\n",
    "\n",
    "        fig_glucose.add_hline(\n",
    "            y=70,\n",
    "            line_dash='dash',\n",
    "            line_color='red'\n",
    "        )\n",
    "\n",
    "        fig_glucose.add_hline(\n",
    "            y=180,\n",
    "            line_dash='dash',\n",
    "            line_color='orange'\n",
    "        )\n",
    "\n",
    "        st.plotly_chart(\n",
    "            fig_glucose,\n",
    "            use_container_width=True\n",
    "        )\n",
    "\n",
    "    with col2:\n",
    "\n",
    "        fig_hist = px.histogram(\n",
    "            df,\n",
    "            x='glucose',\n",
    "            nbins=30,\n",
    "            color='patient_id',\n",
    "            template='plotly_dark',\n",
    "            title='Glucose Distribution'\n",
    "        )\n",
    "\n",
    "        st.plotly_chart(\n",
    "            fig_hist,\n",
    "            use_container_width=True\n",
    "        )\n",
    "\n",
    "    fig_steps = px.area(\n",
    "        df,\n",
    "        x='time',\n",
    "        y='steps',\n",
    "        template='plotly_dark',\n",
    "        title='Daily Physical Activity'\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(\n",
    "        fig_steps,\n",
    "        use_container_width=True\n",
    "    )\n",
    "\n",
    "# =========================================================\n",
    "# DESCRIPTIVE ANALYTICS\n",
    "# =========================================================\n",
    "\n",
    "elif menu == \"Descriptive Analytics\":\n",
    "\n",
    "    st.subheader(\"📊 Descriptive Analytics\")\n",
    "\n",
    "    col1, col2 = st.columns(2)\n",
    "\n",
    "    with col1:\n",
    "\n",
    "        fig_hr = px.scatter(\n",
    "            df,\n",
    "            x='heart_rate',\n",
    "            y='glucose',\n",
    "            color='steps',\n",
    "            size='calories',\n",
    "            template='plotly_dark',\n",
    "            title='Heart Rate vs Glucose'\n",
    "        )\n",
    "\n",
    "        st.plotly_chart(\n",
    "            fig_hr,\n",
    "            use_container_width=True\n",
    "        )\n",
    "\n",
    "    with col2:\n",
    "\n",
    "        fig_sleep = px.box(\n",
    "            df,\n",
    "            x='hour',\n",
    "            y='glucose',\n",
    "            color='hour',\n",
    "            template='plotly_dark',\n",
    "            title='Hourly Glucose Pattern'\n",
    "        )\n",
    "\n",
    "        st.plotly_chart(\n",
    "            fig_sleep,\n",
    "            use_container_width=True\n",
    "        )\n",
    "\n",
    "    corr = df[\n",
    "        [\n",
    "            'glucose',\n",
    "            'heart_rate',\n",
    "            'steps',\n",
    "            'calories',\n",
    "            'sleep_hours'\n",
    "        ]\n",
    "    ].corr()\n",
    "\n",
    "    fig_corr = px.imshow(\n",
    "        corr,\n",
    "        text_auto=True,\n",
    "        template='plotly_dark',\n",
    "        title='Feature Correlation Matrix'\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(\n",
    "        fig_corr,\n",
    "        use_container_width=True\n",
    "    )\n",
    "\n",
    "# =========================================================\n",
    "# PREDICTIVE ANALYTICS\n",
    "# =========================================================\n",
    "\n",
    "elif menu == \"Predictive Analytics\":\n",
    "\n",
    "    st.subheader(\"🤖 Predictive Analytics\")\n",
    "\n",
    "    df['risk_score'] = (\n",
    "        abs(df['glucose_roc']) * 0.4 +\n",
    "        abs(df['glucose_rolling_std']) * 0.4 +\n",
    "        abs(df['heart_rate']) * 0.2\n",
    "    )\n",
    "\n",
    "    fig_risk = px.line(\n",
    "        df,\n",
    "        x='time',\n",
    "        y='risk_score',\n",
    "        template='plotly_dark',\n",
    "        title='Hypoglycemia Risk Prediction'\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(\n",
    "        fig_risk,\n",
    "        use_container_width=True\n",
    "    )\n",
    "\n",
    "    fig_pred = px.scatter(\n",
    "        df,\n",
    "        x='glucose_rolling_std',\n",
    "        y='glucose',\n",
    "        size='steps',\n",
    "        color='risk_score',\n",
    "        template='plotly_dark',\n",
    "        title='Glucose Variability Prediction'\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(\n",
    "        fig_pred,\n",
    "        use_container_width=True\n",
    "    )\n",
    "\n",
    "# =========================================================\n",
    "# PRESCRIPTIVE ANALYTICS\n",
    "# =========================================================\n",
    "\n",
    "elif menu == \"Prescriptive Analytics\":\n",
    "\n",
    "    st.subheader(\"🧠 Prescriptive Recommendations\")\n",
    "\n",
    "    df['Risk_Level'] = np.where(\n",
    "        df['risk_score'] > 50,\n",
    "        'High Risk',\n",
    "        'Stable'\n",
    "    )\n",
    "\n",
    "    fig_intervention = px.scatter(\n",
    "        df,\n",
    "        x='time',\n",
    "        y='glucose',\n",
    "        color='Risk_Level',\n",
    "        size='steps',\n",
    "        template='plotly_dark',\n",
    "        title='AI Intervention Monitoring'\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(\n",
    "        fig_intervention,\n",
    "        use_container_width=True\n",
    "    )\n",
    "\n",
    "    fig_carb = px.density_heatmap(\n",
    "        df,\n",
    "        x='carb_input',\n",
    "        y='insulin',\n",
    "        z='glucose',\n",
    "        template='plotly_dark',\n",
    "        title='Carb vs Insulin Heatmap'\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(\n",
    "        fig_carb,\n",
    "        use_container_width=True\n",
    "    )\n",
    "\n",
    "    st.markdown(\"## 🚨 AI Clinical Recommendations\")\n",
    "\n",
    "    if df['risk_score'].mean() > 40:\n",
    "        st.error(\n",
    "            \"High glucose instability detected. \"\n",
    "            \"Recommend insulin reassessment.\"\n",
    "        )\n",
    "\n",
    "    if df['glucose'].max() > 250:\n",
    "        st.warning(\n",
    "            \"Severe hyperglycemia episodes detected.\"\n",
    "        )\n",
    "\n",
    "    if df['glucose'].min() < 60:\n",
    "        st.info(\n",
    "            \"Hypoglycemia intervention recommended.\"\n",
    "        )\n",
    "\n",
    "# =========================================================\n",
    "# CLINICAL INSIGHTS\n",
    "# =========================================================\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "st.subheader(\"📌 Clinical Insights\")\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "<div class='insight-box'>\n",
    "\n",
    "<b>Key AI Findings:</b><br><br>\n",
    "\n",
    "• High glucose variability predicts future instability.<br><br>\n",
    "\n",
    "• Physical activity improves insulin sensitivity.<br><br>\n",
    "\n",
    "• Large carbohydrate meals increase glucose spikes.<br><br>\n",
    "\n",
    "• Better sleep improves Time-In-Range.<br><br>\n",
    "\n",
    "• AI early-warning systems reduce hypoglycemia risk.\n",
    "\n",
    "</div>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# =========================================================\n",
    "# FOOTER\n",
    "# =========================================================\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "st.caption(\n",
    "    \"Developed using Streamlit + Plotly | \"\n",
    "    \"AI Diabetes Intelligence System\"\n",
    ")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
